credentials_file = "../parsing-text-6492ee9e2cf6.json"
project_id       = "parsing-text"
bucket_name      = "parsing-text-bucket"
topic_name       = "text-parsing-ingestion-request"
subscription_name = "extractor-sub"
